import Foundation

enum HomeCopy {
    enum Key {
        case welcome, commuteHome, nextJourney, liveNow
        case location, locationHint, language, mode, origin, destination
        case serviceAlert, aiRoute, aiLabel, changeStation, startRoute, routeChange, chooseDestination, frequentRoutes, routePlannerPrompt
        case nextTrain, arrivalIn, updatedAt, trainApproaching, loadingTrainData, noNetwork, serviceEnded
        case crowding, exitCarriageRecommendation, metroTogether, metroTogetherSubtitle
        case metroMall, metroMallSubtitle, points, pointsSubtitle, home, routes
        case nearby, wallet, minutes, seconds, simulatedLocation
    }

    static func text(_ key: Key, language: AppLanguage) -> String {
        switch (key, language) {
        case (.welcome, .traditionalChinese): "早安，旅人"
        case (.welcome, .english): "Good morning"
        case (.welcome, .japanese): "おはようございます"
        case (.welcome, .korean): "좋은 아침이에요"
        case (.commuteHome, .traditionalChinese): "通勤首頁"
        case (.commuteHome, .english): "Commute home"
        case (.commuteHome, .japanese): "通勤ホーム"
        case (.commuteHome, .korean): "출퇴근 홈"
        case (.nextJourney, .traditionalChinese): "你的下一段旅程"
        case (.nextJourney, .english): "Your next journey"
        case (.nextJourney, .japanese): "次の移動"
        case (.nextJourney, .korean): "다음 여정"
        case (.liveNow, .traditionalChinese): "即時更新"
        case (.liveNow, .english): "LIVE"
        case (.liveNow, .japanese): "リアルタイム"
        case (.liveNow, .korean): "실시간"
        case (.location, .traditionalChinese): "目前定位"
        case (.location, .english): "YOUR LOCATION"
        case (.location, .japanese): "現在地"
        case (.location, .korean): "현재 위치"
        case (.locationHint, .traditionalChinese): "定位已更新"
        case (.locationHint, .english): "Location updated"
        case (.locationHint, .japanese): "位置情報を更新しました"
        case (.locationHint, .korean): "위치가 업데이트됨"
        case (.language, .traditionalChinese): "語言"
        case (.language, .english): "Language"
        case (.language, .japanese): "言語"
        case (.language, .korean): "언어"
        case (.mode, .traditionalChinese): "使用模式"
        case (.mode, .english): "Mode"
        case (.mode, .japanese): "モード"
        case (.mode, .korean): "모드"
        case (.origin, .traditionalChinese): "起點站"
        case (.origin, .english): "FROM"
        case (.origin, .japanese): "出発駅"
        case (.origin, .korean): "출발역"
        case (.destination, .traditionalChinese): "目的地"
        case (.destination, .english): "DESTINATION"
        case (.destination, .japanese): "目的地"
        case (.destination, .korean): "목적지"
        case (.serviceAlert, .traditionalChinese): "營運公告"
        case (.serviceAlert, .english): "Service alert"
        case (.serviceAlert, .japanese): "運行情報"
        case (.serviceAlert, .korean): "운행 안내"
        case (.aiRoute, .traditionalChinese): "為你推薦的路線"
        case (.aiRoute, .english): "Your suggested route"
        case (.aiRoute, .japanese): "おすすめルート"
        case (.aiRoute, .korean): "추천 경로"
        case (.aiLabel, .traditionalChinese): "AI 智慧推薦"
        case (.aiLabel, .english): "AI ROUTE"
        case (.aiLabel, .japanese): "AI おすすめ"
        case (.aiLabel, .korean): "AI 추천"
        case (.changeStation, .traditionalChinese): "模擬站內定位更新"
        case (.changeStation, .english): "Update demo location"
        case (.changeStation, .japanese): "位置情報を更新"
        case (.changeStation, .korean): "위치 업데이트"
        case (.startRoute, .traditionalChinese): "查看搭乘路線"
        case (.startRoute, .english): "View route"
        case (.startRoute, .japanese): "ルートを見る"
        case (.startRoute, .korean): "경로 보기"
        case (.routeChange, .traditionalChinese): "切換目的地站點"
        case (.routeChange, .english): "Change destination"
        case (.routeChange, .japanese): "目的地を変更"
        case (.routeChange, .korean): "목적지 변경"
        case (.chooseDestination, .traditionalChinese): "手動搜尋目的地"
        case (.chooseDestination, .english): "Search for another destination"
        case (.chooseDestination, .japanese): "別の目的地を検索"
        case (.chooseDestination, .korean): "다른 목적지 검색"
        case (.frequentRoutes, .traditionalChinese): "常用目的地"
        case (.frequentRoutes, .english): "Favorite destinations"
        case (.frequentRoutes, .japanese): "よく使う目的地"
        case (.frequentRoutes, .korean): "즐겨찾는 목적지"
        case (.routePlannerPrompt, .traditionalChinese): "去其他新站點？前往路線規劃"
        case (.routePlannerPrompt, .english): "Looking for another station? Open route planner"
        case (.routePlannerPrompt, .japanese): "別の駅を探す？ルート検索へ"
        case (.routePlannerPrompt, .korean): "다른 역을 찾나요? 경로 계획으로 이동"
        case (.nextTrain, .traditionalChinese): "下一班列車"
        case (.nextTrain, .english): "Next train"
        case (.nextTrain, .japanese): "次の列車"
        case (.nextTrain, .korean): "다음 열차"
        case (.arrivalIn, .traditionalChinese): "抵達倒數"
        case (.arrivalIn, .english): "ARRIVES IN"
        case (.arrivalIn, .japanese): "到着まで"
        case (.arrivalIn, .korean): "도착까지"
        case (.updatedAt, .traditionalChinese): "更新於"
        case (.updatedAt, .english): "Updated"
        case (.updatedAt, .japanese): "更新"
        case (.updatedAt, .korean): "업데이트"
        case (.trainApproaching, .traditionalChinese): "列車進站中"
        case (.trainApproaching, .english): "Train arriving"
        case (.trainApproaching, .japanese): "まもなく到着"
        case (.trainApproaching, .korean): "열차 진입 중"
        case (.loadingTrainData, .traditionalChinese): "正在取得列車資訊"
        case (.loadingTrainData, .english): "Loading train data"
        case (.loadingTrainData, .japanese): "列車情報を取得中"
        case (.loadingTrainData, .korean): "열차 정보 불러오는 중"
        case (.noNetwork, .traditionalChinese): "無網路，暫無即時資料"
        case (.noNetwork, .english): "Offline — live data unavailable"
        case (.noNetwork, .japanese): "オフライン — 情報なし"
        case (.noNetwork, .korean): "오프라인 — 실시간 정보 없음"
        case (.serviceEnded, .traditionalChinese): "末班車已過"
        case (.serviceEnded, .english): "Service has ended"
        case (.serviceEnded, .japanese): "本日の運行は終了しました"
        case (.serviceEnded, .korean): "운행이 종료되었습니다"
        case (.crowding, .traditionalChinese): "車廂擁擠度"
        case (.crowding, .english): "Car occupancy"
        case (.crowding, .japanese): "車内の混雑度"
        case (.crowding, .korean): "객차 혼잡도"
        case (.exitCarriageRecommendation, .traditionalChinese): "推薦車廂"
        case (.exitCarriageRecommendation, .english): "Recommended cars"
        case (.exitCarriageRecommendation, .japanese): "おすすめ車両"
        case (.exitCarriageRecommendation, .korean): "추천 칸"
        case (.metroTogether, .traditionalChinese): "捷客電台"
        case (.metroTogether, .english): "MetroTogether"
        case (.metroTogether, .japanese): "Metro Together"
        case (.metroTogether, .korean): "Metro Together"
        case (.metroTogetherSubtitle, .traditionalChinese): "和城市一起探索"
        case (.metroTogetherSubtitle, .english): "Explore the city together"
        case (.metroTogetherSubtitle, .japanese): "街を一緒に楽しもう"
        case (.metroTogetherSubtitle, .korean): "도시를 함께 탐험해요"
        case (.metroMall, .traditionalChinese): "捷運商城"
        case (.metroMall, .english): "Metro Mall"
        case (.metroMall, .japanese): "メトロモール"
        case (.metroMall, .korean): "메트로 몰"
        case (.metroMallSubtitle, .traditionalChinese): "沿線好物一次逛"
        case (.metroMallSubtitle, .english): "Shop along your route"
        case (.metroMallSubtitle, .japanese): "沿線のアイテムをチェック"
        case (.metroMallSubtitle, .korean): "노선 주변 쇼핑"
        case (.points, .traditionalChinese): "搭點活動"
        case (.points, .english): "Ride & earn"
        case (.points, .japanese): "乗車ポイント"
        case (.points, .korean): "탑승 포인트"
        case (.pointsSubtitle, .traditionalChinese): "搭乘集點享好康"
        case (.pointsSubtitle, .english): "Ride, collect, redeem"
        case (.pointsSubtitle, .japanese): "乗って貯めて交換"
        case (.pointsSubtitle, .korean): "타고 적립하고 사용해요"
        case (.home, .traditionalChinese): "首頁"
        case (.home, .english): "Home"
        case (.home, .japanese): "ホーム"
        case (.home, .korean): "홈"
        case (.routes, .traditionalChinese): "路線"
        case (.routes, .english): "Routes"
        case (.routes, .japanese): "路線"
        case (.routes, .korean): "노선"
        case (.nearby, .traditionalChinese): "附近"
        case (.nearby, .english): "Nearby"
        case (.nearby, .japanese): "周辺"
        case (.nearby, .korean): "주변"
        case (.wallet, .traditionalChinese): "我的"
        case (.wallet, .english): "My account"
        case (.wallet, .japanese): "マイページ"
        case (.wallet, .korean): "내 정보"
        case (.minutes, .traditionalChinese): "分"
        case (.minutes, .english): "m"
        case (.minutes, .japanese): "分"
        case (.minutes, .korean): "분"
        case (.seconds, .traditionalChinese): "秒"
        case (.seconds, .english): "s"
        case (.seconds, .japanese): "秒"
        case (.seconds, .korean): "초"
        case (.simulatedLocation, .traditionalChinese): "示範定位"
        case (.simulatedLocation, .english): "Demo location"
        case (.simulatedLocation, .japanese): "デモ位置情報"
        case (.simulatedLocation, .korean): "데모 위치"
        }
    }

    static func stationName(_ station: String, language: AppLanguage) -> String {
        switch (station.replacingOccurrences(of: "站", with: ""), language) {
        case ("台北車", .traditionalChinese): "台北車站"
        case ("台北車", .english): "Taipei Main"
        case ("台北車", .japanese): "台北駅"
        case ("台北車", .korean): "타이베이 메인역"
        case ("市政府", .traditionalChinese): "市政府"
        case ("市政府", .english): "Taipei City Hall"
        case ("市政府", .japanese): "市政府駅"
        case ("市政府", .korean): "시정부역"
        case ("象山", .traditionalChinese): "象山"
        case ("象山", .english): "Xiangshan"
        case ("象山", .japanese): "象山"
        case ("象山", .korean): "샹산"
        case ("廣慈/奉天宮", .traditionalChinese): "廣慈／奉天宮"
        case ("廣慈/奉天宮", .english): "Guangci/Fengtian Temple"
        case ("廣慈/奉天宮", .japanese): "広慈／奉天宮"
        case ("廣慈/奉天宮", .korean): "광츠·펑톈궁"
        case ("公館", .traditionalChinese): "公館"
        case ("公館", .english): "Gongguan"
        case ("公館", .japanese): "公館"
        case ("公館", .korean): "궁관"
        case ("板橋", .traditionalChinese): "板橋"
        case ("板橋", .english): "Banqiao"
        case ("板橋", .japanese): "板橋"
        case ("板橋", .korean): "반차오"
        case ("淡水", .traditionalChinese): "淡水"
        case ("淡水", .english): "Tamsui"
        case ("淡水", .japanese): "淡水"
        case ("淡水", .korean): "단수이"
        case ("西門", .traditionalChinese): "西門"
        case ("西門", .english): "Ximen"
        case ("西門", .japanese): "西門"
        case ("西門", .korean): "시먼"
        default: station
        }
    }

    static func favoriteTitle(_ id: String, fallback: String, language: AppLanguage) -> String {
        switch (id, language) {
        case ("home", .traditionalChinese): "回家"
        case ("home", .english): "Home"
        case ("home", .japanese): "自宅"
        case ("home", .korean): "집"
        case ("office", .traditionalChinese): "去公司"
        case ("office", .english): "Work"
        case ("office", .japanese): "会社"
        case ("office", .korean): "회사"
        case ("family", .traditionalChinese): "去家人家"
        case ("family", .english): "Family"
        case ("family", .japanese): "家族"
        case ("family", .korean): "가족"
        case ("school", .traditionalChinese): "學校"
        case ("school", .english): "School"
        case ("school", .japanese): "学校"
        case ("school", .korean): "학교"
        case ("custom", .traditionalChinese): "自訂站點"
        case ("custom", .english): "Custom station"
        case ("custom", .japanese): "駅を選ぶ"
        case ("custom", .korean): "역 선택"
        default: fallback
        }
    }
}
