import Foundation

enum TourismHomeCopy {
    enum Key {
        case title, generalMode, elevatorRoute, avoidStairs, transfer, transferStation, total, guide, elevatorExit, recommendedExit
        case luggageCars, attractionExit, quickActions, passWallet, locker, airport, assistance
        case passSubtitle, lockerSubtitle, airportSubtitle, assistanceSubtitle, aiRoute, aiRouteSubtitle
    }

    static func text(_ key: Key, language: TourismLanguage) -> String {
        switch (key, language) {
        case (.title, .traditionalChinese): "觀光模式"
        case (.title, .english): "Tourist mode"
        case (.title, .japanese): "観光モード"
        case (.title, .korean): "관광 모드"
        case (.generalMode, .traditionalChinese): "返回一般模式"
        case (.generalMode, .english): "General mode"
        case (.generalMode, .japanese): "通常モード"
        case (.generalMode, .korean): "일반 모드"
        case (.elevatorRoute, .traditionalChinese): "全段電梯導航"
        case (.elevatorRoute, .english): "Elevator-first route"
        case (.elevatorRoute, .japanese): "エレベーター優先ルート"
        case (.elevatorRoute, .korean): "엘리베이터 우선 경로"
        case (.avoidStairs, .traditionalChinese): "避開階梯"
        case (.avoidStairs, .english): "Avoid stairs"
        case (.avoidStairs, .japanese): "階段を避ける"
        case (.avoidStairs, .korean): "계단 피하기"
        case (.transfer, .traditionalChinese): "轉乘"
        case (.transfer, .english): "Transfer"
        case (.transfer, .japanese): "乗換"
        case (.transfer, .korean): "환승"
        case (.transferStation, .traditionalChinese): "建議轉乘站"
        case (.transferStation, .english): "Suggested transfer"
        case (.transferStation, .japanese): "おすすめ乗換駅"
        case (.transferStation, .korean): "추천 환승역"
        case (.total, .traditionalChinese): "預計乘車時間"
        case (.total, .english): "Estimated travel time"
        case (.total, .japanese): "予想乗車時間"
        case (.total, .korean): "예상 탑승 시간"
        case (.guide, .traditionalChinese): "電梯指引"
        case (.guide, .english): "Elevator guide"
        case (.guide, .japanese): "エレベーター案内"
        case (.guide, .korean): "엘리베이터 안내"
        case (.elevatorExit, .traditionalChinese): "電梯"
        case (.elevatorExit, .english): "Elevator"
        case (.elevatorExit, .japanese): "エレベーター"
        case (.elevatorExit, .korean): "엘리베이터"
        case (.recommendedExit, .traditionalChinese): "推薦最佳出口"
        case (.recommendedExit, .english): "Recommended exit"
        case (.recommendedExit, .japanese): "おすすめ出口"
        case (.recommendedExit, .korean): "추천 출구"
        case (.luggageCars, .traditionalChinese): "大行李車廂"
        case (.luggageCars, .english): "Luggage-friendly cars"
        case (.luggageCars, .japanese): "荷物に便利な車両"
        case (.luggageCars, .korean): "짐이 편한 객차"
        case (.attractionExit, .traditionalChinese): "景點電梯出口"
        case (.attractionExit, .english): "Attraction elevator exit"
        case (.attractionExit, .japanese): "観光地のエレベーター出口"
        case (.attractionExit, .korean): "관광지 엘리베이터 출구"
        case (.quickActions, .traditionalChinese): "旅遊快捷入口"
        case (.quickActions, .english): "Travel quick actions"
        case (.quickActions, .japanese): "観光クイックアクション"
        case (.quickActions, .korean): "여행 빠른 실행"
        case (.passWallet, .traditionalChinese): "觀光 Pass & 票券錢包"
        case (.passWallet, .english): "Pass & ticket wallet"
        case (.passWallet, .japanese): "パス・チケットウォレット"
        case (.passWallet, .korean): "패스 및 승차권 지갑"
        case (.locker, .traditionalChinese): "Locker 寄物櫃與托運"
        case (.locker, .english): "Lockers & baggage service"
        case (.locker, .japanese): "ロッカー・手荷物預かり"
        case (.locker, .korean): "보관함 및 수하물 서비스"
        case (.airport, .traditionalChinese): "機場捷運 & 預辦登機"
        case (.airport, .english): "Airport MRT & pre-check-in"
        case (.airport, .japanese): "空港MRT・事前チェックイン"
        case (.airport, .korean): "공항 MRT 및 사전 체크인"
        case (.assistance, .traditionalChinese): "站務人員支援通報"
        case (.assistance, .english): "Station assistance"
        case (.assistance, .japanese): "駅係員サポート"
        case (.assistance, .korean): "역무원 지원 요청"
        case (.aiRoute, .traditionalChinese): "熱門觀光路線與導覽"
        case (.aiRoute, .english): "Popular routes & guides"
        case (.aiRoute, .japanese): "人気ルート・ガイド"
        case (.aiRoute, .korean): "인기 관광 경로 및 가이드"
        case (.passSubtitle, .traditionalChinese): "Taipei Pass · Fun Pass · QR"
        case (.passSubtitle, .english): "Taipei Pass · Fun Pass · QR"
        case (.passSubtitle, .japanese): "Taipei Pass · Fun Pass · QR"
        case (.passSubtitle, .korean): "Taipei Pass · Fun Pass · QR"
        case (.lockerSubtitle, .traditionalChinese): "即時空位與位置"
        case (.lockerSubtitle, .english): "Live spaces & directions"
        case (.lockerSubtitle, .japanese): "空き状況と案内"
        case (.lockerSubtitle, .korean): "실시간 여유 및 위치"
        case (.airportSubtitle, .traditionalChinese): "A1 台北車站"
        case (.airportSubtitle, .english): "A1 Taipei Main Station"
        case (.airportSubtitle, .japanese): "A1 台北駅"
        case (.airportSubtitle, .korean): "A1 타이베이 메인역"
        case (.assistanceSubtitle, .traditionalChinese): "一鍵聯絡站務"
        case (.assistanceSubtitle, .english): "Contact station staff"
        case (.assistanceSubtitle, .japanese): "係員へ連絡"
        case (.assistanceSubtitle, .korean): "역무원에게 연락"
        case (.aiRouteSubtitle, .traditionalChinese): "AI 推薦景點與無障礙路線"
        case (.aiRouteSubtitle, .english): "AI picks for your next stop"
        case (.aiRouteSubtitle, .japanese): "AIおすすめの観光ルート"
        case (.aiRouteSubtitle, .korean): "AI 추천 관광 경로"
        }
    }
}
